<?php

namespace Enginewerk\MapdzillaBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Enginewerk\MapdzillaBundle\Entity\Node;

/**
 * NodeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NodeRepository extends EntityRepository
{
    public function getDomainsForUser(User $user)
    {
        $queryBuilder = $this->createQueryBuilder('d');
        $query = $queryBuilder
            ->where($queryBuilder->expr()->eq('d.user', ':user'))
            ->setParameter('user', $user)
            ->orderBy('d.name', 'ASC')
            ->getQuery()
            ;

        return $query->getResult();
    }

}
