<?php

namespace Enginewerk\MapdzillaBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Enginewerk\MapdzillaBundle\Entity\Node;

/**
 * NodeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NodeRepository extends EntityRepository
{
    public function findAllJSON($lat, $lon, $radius)
    {
        $queryBuilder = $this->createQueryBuilder('n');
        $queryBuilder
                ->setMaxResults($radius * 5)
                ->where('n.way IS NULL');

        return $queryBuilder
                ->getQuery()
                ->getResult();
    }
}
